### ISSUE TITLE
-kvi, -kvt, -kvs error

### ISSUE THREAD

**Issue by OEI-Cgray** [vcsjones/AzureSignTool#103]
Hello, when using these three options, which the instructions imply are needed to all be used together, I get the following error:

```
AzureSignTool.exe sign --description "Some description" --description-url "https://a-url.net/" --azure-key-vault-url https://akeyvaulturl.vault.azure.net/ --azure-key-vault-client-id aadID --azure-key-vault-client-secret password --azure-key-vault-tenant-id aadID --azure-key-vault-certificate nameofcert --timestamp-rfc3161 http://timestamp.digicert.com/ --verbose C:\Some\File\Path.exe

echo %ERRORLEVEL%
-2147024809
```

Using just --azure-key-vault-client-id and --azure-key-vault-client-secret works fine though, so not sure if this is just stale docs or a bug.

**Comment by vcsjones** [comment]
The `--azure-key-vault-tenant-id` is a required parameter for a version of AST that has not been released yet (working on that). See the readme for the current tag for docs about the released version here: https://github.com/vcsjones/AzureSignTool/blob/v2.0.17/README.md

Sorry for the confusion, I'll try to fix-up the README documentation so that it isn't covering something that is unreleased.
