### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by Kormyr** [vcsjones/AzureSignTool#217]
Hello,

.NET 6 will be end of support on November 12, 2024.
Now that the next LTS has been released, are there any plans for the tool to support .NET 8?

Thanks.

**Comment by Kormyr** [comment]
For anyone experiencing the same problems and want a quick workaround, I generated standalone .NET 8 executables: https://github.com/Kormyr/AzureSignTool/releases/tag/v1.0
I am still hoping they will be provided soon on this repository.

**Comment by vcsjones** [comment]
I expect to have a .NET 8 release out by the end of this year, 2023.

**Comment by TheodorKleynhans** [comment]
I see that the [PR to add .NET 8 support](https://github.com/vcsjones/AzureSignTool/pull/221) was completed a month ago.
Is there a reason why it is being held back? Is there something I can do to help get it released?

**Comment by lumzl** [comment]
Yes, any info would be great thanks.

**Comment by caracostea** [comment]
@vcsjones Any chance for the release containing support for .NET8 to happen soon?

**Comment by vcsjones** [comment]
Sorry for the delay here. I was initially hoping to be able to produce independent executables with self-contained deployments, in addition to publishing on NuGet. This turned out to be a bigger task than I thought, and it seemed like I was "really close" for quite a while there. Instead I will give up on it for now and get a version out on NuGet this weekend, and publish self-contained executables if and when I figure out it.

Sorry for the hold up there.

**Comment by vcsjones** [comment]
AzureSignTool 8.0.0 is out and bumps to .NET 8.0.
