### ISSUE TITLE
Silent failiure in v. 2.0.17

### ISSUE THREAD

**Issue by mste-milestonedk** [vcsjones/AzureSignTool#225]
Hi

I tried to run v. 2.0.17 of azuresigntool.exe as specified by our local IT-department, it failed silently every time. No output and no errors.
When I upgraded to v. 4.0.1 it run fine as it should.

The only time time I could get v. 2.0.17 to output something was when I provided an option without value. Then I got a stack trace.

It is for me extremely worrying that the tool can fail silently. It makes error handling almost impossible, and cause releases without signing.

I hope, but am in no way certain, that v. 4.0.1 wont fail silently in some use cases. 

I would recommend a hotfix for every affected major version.

Regards,
/Martin

**Comment by vcsjones** [comment]
Old versions of AzureSignTool had a bug in them where a malformed or incorrect parameter configuration would silently exit. This was fixed many years ago in version 3.0.

> 2.0.17

That version is over 5 years old and is the first version of AzureSignTool to be publicly released.

> cause releases without signing.

Are you checking the exit code of AzureSignTool? AzureSignTool never exits with a successful error code unless signing completed fully successfully. That is the definitive way to know if the tool succeeded or not.

> I would recommend a hotfix for every affected major version.

The affected version is 2.0.17, it was fixed in 3.0, and I don't support anything but the latest version. Your IT department should update its guidance to use the latest version.
