### ISSUE TITLE
Error 80072EFD

### ISSUE THREAD

**Issue by FigBug** [vcsjones/AzureSignTool#226]
Everything was working fine until today and now signing is failing with error 80072EFD. I have not changed anything in my code or on Azure. 

I'm trying to identify if this is an issue on Azure but the error message is not very helpful. Is there a way to get more info about the error?

The logs look like this:

```
trce: AzureSignTool.SignCommand[0]
      Retrieving certificate ***.
trce: AzureSignTool.SignCommand[0]
      Retrieved certificate ***.
trce: AzureSignTool.SignCommand[0]
      Creating context
info: AzureSignTool.SignCommand[0]
      Signing file.
trce: AzureSignTool.SignCommand[0]
      Getting SIP Data
trce: AzureSignTool.SignCommand[0]
      Calling SignerSignEx3
fail: AzureSignTool.SignCommand[0]
      Signing failed with error 80072EFD.
info: AzureSignTool.SignCommand[0]
      Stopping file signing.
info: AzureSignTool.SignCommand[0]
      Successful operations: 0
info: AzureSignTool.SignCommand[0]
      Failed operations: 1
Error: Process completed with exit code 2.
```

**Comment by vcsjones** [comment]
That error is `WININET_E_CANNOT_CONNECT` I believe. This probably means that timestamping is failing. This can happen when

1. Something changed in your network configuration and your specified timestamp server cannot be reached.
2. The timestamp server has blocked or is throttling your IP address because you are submitting too many timestamp requests for them.

Can you try another timestamp server?

**Comment by FigBug** [comment]
A different server resolved it, thanks
