### ISSUE TITLE
SignFile returning code -2146762749

### ISSUE THREAD

**Issue by steveellis** [vcsjones/AzureSignTool#60]
I'm coming to this from @onovotny's https://github.com/onovotny/SignService which includes this library.

I'm seeing`AuthenticodeKeyVaultSigner.SignFile` return a code of -2146762749 which googling tells me may be coming from something called `WinTrust` or `WinVerifyTrust`.  In my case I suspect this is because I am testing with a certificate that is self-signed.

Does anyone have any thoughts on this? Am I on the right track with this or is this likely something else? Should I expect this to work with a self-signed certificate?

**Comment by onovotny** [comment]
The tool should work with a self-signed certificate. I use that regularly for my testing (though I believe the dates must be valid).

@vcsjones would know more.

**Comment by vcsjones** [comment]
-2146762749 (in hex 0x800B0003) is TRUST_E_SUBJECT_FORM_UNKNOWN.

The most _common_ cause of this error is when you try to sign a file and there is no SIP in the system for that file type. Put another way, Windows doesn't know how to sign that file type. For example, if I use the stand alone CLI version of `AzureSignTool` and I try to sign a non-empty text file, I get this:

```
info: AzureSignTool.Program[0]
      => File: foo.txt
      Signing file foo.txt
fail: AzureSignTool.Program[0]
      => File: foo.txt
      Signing failed with error 800B0003 for file foo.txt.
info: AzureSignTool.Program[0]
      => File: foo.txt
      Stopping file signing.
info: AzureSignTool.Program[0]
      Successful operations: 0
```

Putting `unchecked((int)0x800B0003)` into LinqPad gives me back `-2146762749`.

This can might happen when you try to sign a file that has a DLL, EXE, extension but is not really a portable executable, or is otherwise corrupt. However other error codes might be encountered first.

1. Can you provide more details about the file being signed that is returning this error? Is it an EXE, MSI, etc.
2. Can you confirm it is a "real" version of that extension type, not just a text file with an EXE extension?
3. Can you please tell us more about the version of Windows you are using? Which version, build, 32-bit vs 64-bit, etc.
4. If everything seems to indicate that the file _should_ be sign-able, can you try signing the file that is not signing correctly using the CLI version of AzureSignTool? It can be installed with `dotnet tool install --global AzureSignTool` if you have .NET Core 2.1 installed. See the README for usage.

**Comment by vcsjones** [comment]
>This can might happen when you try to sign a file that has a DLL, EXE, extension but is not really a portable executable, or is otherwise corrupt. However other error codes might be encountered first.

I confirmed this error also happens when you try to sign a file with the right extension, but isn't really that file type. For example, if I make a text file with the contents "hello world", change the extension to EXE, and try to sign it...

```
info: AzureSignTool.Program[0]
      => File: foo.exe
      Signing file foo.exe
fail: AzureSignTool.Program[0]
      => File: foo.exe
      Signing failed with error 800B0003 for file foo.exe.
info: AzureSignTool.Program[0]
      => File: foo.exe
      Stopping file signing.
info: AzureSignTool.Program[0]
      Successful operations: 0
```

Same error.

I don't think SignService will feed this library a file with the wrong extension unless it has the `MZ` magic bytes. My current suspicion then you are trying to sign a file that has an EXE, DLL, or any other "PE" extension but isn't really that kind of file.

**Comment by vcsjones** [comment]
The extension list is here in SignService. So I suspect the issue is you're trying to sign a file with one of these extensions that is not a "real" one of those files. Knowing more about the file that produced this issue will be key to solving it.

https://github.com/onovotny/SignService/blob/656ad1643ce3e402c34aa6e774965009a32526f8/src/SignService/SigningTools/AzureSignToolSignService.cs#L136-L159

**Comment by steveellis** [comment]
@onovotny and @vcsjones thank you for your thoughts on this! Kevin you are exactly right. I was testing with text file that i just added an .exe too... As soon as changed it to a real exe file everything worked.

**Comment by Dahbe** [comment]
hi,
So it is not possible to sign device guard policy. 
After converting the policy file from XML to Bin (ConvertFrom-CIPolicy command). I got the error:
Signing failed with error 800B0003 for file SIPolicy.bin
When using signtool of sdk the command below works:
Signtool sign /f MyCert.pfx /t http://timestamp.digicert.com MyFile.pb7 /p7 "Directory " -p7co 1.3.6.1.4.1.311.79.1 /fd sha256

**Comment by vcsjones** [comment]
@Dahbe Interesting. I'll take a look at that. Can you file a new issue?
