### ISSUE TITLE
Signing fails with 80072EE2 error

### ISSUE THREAD

**Issue by akamisarau** [vcsjones/AzureSignTool#79]
Randomly, signing fails with an error:
`trce: AzureSignTool.Program[0]
      Retrieving certificate certName.
trce: AzureSignTool.Program[0]
      Retrieved certificate certName.
trce: AzureSignTool.Program[0]
      Creating context
info: AzureSignTool.Program[0]
      => File: F:\agent1\_work\3\a\publish\fileName.exe
      Signing file F:\agent1\_work\3\a\publish\fileName.exe
trce: AzureSignTool.Program[0]
      => File: F:\agent1\_work\3\a\publish\fileName.exe
      Getting SIP Data
trce: AzureSignTool.Program[0]
      => File: F:\agent1\_work\3\a\publish\fileName.exe
      Calling SignerSignEx3
fail: AzureSignTool.Program[0]
      => File: F:\agent1\_work\3\a\publish\fileName.exe
      Signing failed with error 80072EE2 for file F:\agent1\_work\3\a\publish\fileName.exe.
info: AzureSignTool.Program[0]
      => File: F:\agent1\_work\3\a\publish\fileName.exe
      Stopping file signing.
info: AzureSignTool.Program[0]
      Successful operations: 0
info: AzureSignTool.Program[0]
      Failed operations: 1`
It can happen either for dll or exe files.
Simple retry does not help. Sometimes it works normally after the machine restart.

**Comment by vcsjones** [comment]
0x8007???? is usually reserved for converting [Win32 Error Codes to HRESULTs][2]. If we take 2EE2 and convert that to decimal... that is 12002. [Microsoft support indicates][1] this is the error code for `ERROR_INTERNET_TIMEOUT`.

I assume you are using AzureSignTool to perform timestamping? I suspect the problem is your server is unable to communicate with the timestamp server. Either because your server is having intermittent connectivity issues, or because the timestamp server is throttling timestamp requests.


[1]: https://support.microsoft.com/en-us/help/193625/info-wininet-error-codes-12001-through-12156
[2]: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/0c0bcf55-277e-4120-b5dc-f6115fc8dc38

**Comment by akamisarau** [comment]
I tried already to set several retries, but maybe 5 minutes is not enough. The machine we use is just a VM in Azure, so network must be more or less stable.
Anyway thank you for the idea, I will try to increase the interval and number of attempts.

**Comment by vcsjones** [comment]
As an experiment, you could try disabling timestamping to see if that addresses the reliability. You should definitely be timestamping, but it might help narrow down the problem.

**Comment by akamisarau** [comment]
Actually yes. Without timestamping it is always successful. So I added several timestamp services to use in a loop in case of timeout and now it works as expected.
Thank you for the advice!

**Comment by tyrel-alastair-hunter-bosch** [comment]
@vcsjones it seems that when this tool is used in a CI environment that it is not good to have to manually retry when a timestamp server throttles the request. It might be a good idea for the tool to have a command line option to try a backup timestamp server and maybe to throttle the requests to the timestamp server, and possibly even specify a retry limit in case an intermittent internet connection failure.
